services:
  app:
    build: .  # 現在のディレクトリにあるDockerfileを使ってイメージをビルド
    container_name: app
    environment:
      - PYTHONUNBUFFERED=1  # Pythonの標準出力をバッファリングしない設定
    command: /bin/bash  # コンテナ起動時に/bin/bashを実行
    volumes:
      - ./src:/app/src  # srcディレクトリをコンテナ内の/app/srcにマウント
      - ./tests:/app/tests  # testsディレクトリをコンテナ内の/app/testsにマウント
      - ./data:/app/data  # dataディレクトリをコンテナ内の/app/dataにマウント
    tty: true  # TTYモードを有効にする
    stdin_open: true  # 標準入力を開いたままにする


# ymlについてはbashに入る方法がいまひとつわからんのでいったん断念。
# とりあえずは 以下のcontainer runコマンドを手打ちで実行することにします。
# docker container run --name app --rm --interactive --tty --volume $(pwd)/src:/app/src --volume $(pwd)/tests:/app/tests --volume $(pwd)/data:/data python-practice bash

# サードパーティライブラリを新しくインストールするため、requirement.txtを書き換えた場合などは、以下のコマンドでイメージをリビルドしてください
# docker image build --tag python-practice .